package com.dms.model.entity;
// Generated 26-May-2014 11:50:44 by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

/**
 * Connections generated by hbm2java
 */
@Entity
@Audited
@Table(name="connection")
public class Connection  extends BaseEntity implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="idCONNECTION", unique=true, nullable=false)
    private Integer idConnection;
	
	@Temporal(TemporalType.TIMESTAMP)
    @Column(name="DATE_CONNECTED", length=19)
    private Date dateConnected;
	
	@Column(name="IP", length=200)
    private String ip;
	
	@Column(name="PASSWORD", length=200)
    private String password;
	
	@Column(name="USER", length=200)
    private String user;
	
	@Column(name="HOST", length=200)
    private String host;
	
	@Column(name="PORT", length=200)
    private String port;
	
	@Column(name="REQ_USER", length=200)
    private String reqUser;
	
	@Column(name="URI", length=200)
    private String uri;
	
	@Column(name="URL", length=200)
    private String url;
	
	@Column(name="USER_AGENT", length=500)
	private String userAgent;

    public Connection() {
    }
  
    public Integer getIdConnection() {
        return this.idConnection;
    }
    
    public void setIdConnection(Integer idConnection) {
        this.idConnection = idConnection;
    }

    public Date getDateConnected() {
        return this.dateConnected;
    }
    
    public void setDateConnected(Date dateConnected) {
        this.dateConnected = dateConnected;
    }

    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }

    
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }

    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }

    public String getPort() {
        return this.port;
    }
    
    public void setPort(String port) {
        this.port = port;
    }

    
    public String getReqUser() {
        return this.reqUser;
    }
    
    public void setReqUser(String reqUser) {
        this.reqUser = reqUser;
    }

    public String getUri() {
        return this.uri;
    }
    
    public void setUri(String uri) {
        this.uri = uri;
    }

    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

	public String getUserAgent() {
		return userAgent;
	}

	public void setUserAgent(String userAgent) {
		this.userAgent = userAgent;
	}




}


