package com.dms.model.entity;
// Generated 26-May-2014 11:50:44 by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.ColumnResult;
import javax.persistence.ConstructorResult;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedNativeQuery;
import javax.persistence.OneToOne;
import javax.persistence.SqlResultSetMapping;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.envers.Audited;

import com.dms.model.domain.DocumentDetails;
import com.dms.utils.DbUtils;

/**
 * Document generated by hbm2java
 */


@Entity
@Audited
@Table(name="document")
@NamedNativeQuery(
        name="findAllDocumentDetails",
        query=DbUtils.SQL_DOCUMENT_DETAILS,
        resultSetMapping="document-details"
      )
      @SqlResultSetMapping(name="document-details",
        classes={
          @ConstructorResult(targetClass=DocumentDetails.class, columns={
              @ColumnResult(name="ID", type=Integer.class),
              @ColumnResult(name="INDEXED_DATE", type=Date.class),
              @ColumnResult(name="DATE_ON_LETTER", type=Date.class),
              @ColumnResult(name="PER_FROM_NAME", type=String.class),
              @ColumnResult(name="PER_TO_NAME", type=String.class),
              @ColumnResult(name="PER_FROM_ID", type=Integer.class),
              @ColumnResult(name="PER_TO_ID", type=Integer.class),
              @ColumnResult(name="TYP_NAME", type=String.class),
              @ColumnResult(name="TYP_ID", type=Integer.class),
              @ColumnResult(name="COM_TEXT", type=String.class),
              @ColumnResult(name="EXT", type=String.class),
              @ColumnResult(name="CREATED_BY", type=String.class),
              @ColumnResult(name="AUTO_INSERTED", type=Boolean.class),
          })
        }
      )

public class Document  extends BaseEntity implements java.io.Serializable {

	 private static final long serialVersionUID = 1L;

     @Id @GeneratedValue(strategy=IDENTITY)
     @Column(name="ID", unique=true, nullable=false)
     private Integer id;
     
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SENT_FROM_PER_ID")
     private Person personByDocSentFromPerId;
     
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="TYP_ID")
     private Type type;
     
     @ManyToOne(fetch=FetchType.LAZY)
     @JoinColumn(name="SENT_TO_PER_ID")
     private Person personByDocSentToPerId;
     
     @Column(name="FILENAME", length=4000)
     private String filename;
     
     @Temporal(TemporalType.DATE)
     @Column(name="INDEXED_DATE", length=10)
     private Date indexedDate;
     
     @Column(name="COM_TEXT", length=500)
     private String comText;
     
     @Column(name="EXT", length=30)
     private String ext;
     
     @Temporal(TemporalType.DATE)
     @Column(name="DATE_ON_LETTER", length=10)
     private Date dateOnLetter;
     
     @Column(name="AUTO_INSERTED")
     private Boolean autoInserted;
     
     @OneToOne(mappedBy="document", cascade=CascadeType.ALL)
     @JoinColumn(name="LET_ID")
     private Letter letter;

    public Document() {
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Person getPersonByDocSentFromPerId() {
        return this.personByDocSentFromPerId;
    }
    
    public void setPersonByDocSentFromPerId(Person personByDocSentFromPerId) {
        this.personByDocSentFromPerId = personByDocSentFromPerId;
    }

    public Type getType() {
        return this.type;
    }
    
    public void setType(Type type) {
        this.type = type;
    }

    public Person getPersonByDocSentToPerId() {
        return this.personByDocSentToPerId;
    }
    
    public void setPersonByDocSentToPerId(Person personByDocSentToPerId) {
        this.personByDocSentToPerId = personByDocSentToPerId;
    }

    
    public String getFilename() {
        return this.filename;
    }
    
    public void setFilename(String filename) {
        this.filename = filename;
    }

    public Date getIndexedDate() {
        return this.indexedDate;
    }
    
    public void setIndexedDate(Date indexedDate) {
        this.indexedDate = indexedDate;
    }

    public String getComText() {
        return this.comText;
    }
    
    public void setComText(String comText) {
        this.comText = comText;
    }
    
    public String getExt() {
        return this.ext;
    }
    
    public void setExt(String ext) {
        this.ext = ext;
    }

    public Date getDateOnLetter() {
        return this.dateOnLetter;
    }
    
    public void setDateOnLetter(Date dateOnLetter) {
        this.dateOnLetter = dateOnLetter;
    }


    public Boolean getAutoInserted() {
        return this.autoInserted;
    }
    
    public void setAutoInserted(Boolean autoInserted) {
        this.autoInserted = autoInserted;
    }

    public Letter getLetter() {
		return letter;
	}

	public void setLetter(Letter letter) {
		this.letter = letter;
	}



}


