package com.dms.model.entity;

// Generated 26-May-2014 11:50:44 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * LetterText generated by hbm2java
 */
@Entity
@Audited
@Table(name = "letter_text")
public class LetterText extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LET_ID")
	private Letter letter;

	@Column(name = "SEQUENCE")
	private Integer sequence;

	@Column(name = "TEXT", length = 4000)
	private String text;

	@Column(name = "EXTRACT", length = 1000)
	private String extract;

	public LetterText() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Letter getLetter() {
		return letter;
	}

	public void setLetter(Letter letter) {
		this.letter = letter;
	}



	public Integer getSequence() {
		return sequence;
	}



	public void setSequence(Integer sequence) {
		this.sequence = sequence;
	}



	public String getText() {
		return text;
	}



	public void setText(String text) {
		this.text = text;
	}



	public String getExtract() {
		return extract;
	}



	public void setExtract(String extract) {
		this.extract = extract;
	}

}
