package com.dms.model.entity;
// Generated 26-May-2014 11:50:44 by Hibernate Tools 3.4.0.CR1


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * Types generated by hbm2java
 */
@Entity
@Audited
@Table(name="type")
public class Type  extends BaseEntity implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id @GeneratedValue(strategy=IDENTITY)
	@Column(name="TYP_ID", unique=true, nullable=false)
    private Integer typId;
	
	@Column(name="NAME", length=4000)
    private String name;
	
	@Column(name="CATEGORY", length=3)
    private String category;
	
	@Column(name="SORT_ORDER")
    private Integer sortOrder;

    public Type() {
    }
     
    public Integer getTypId() {
        return this.typId;
    }
    
    public void setTypId(Integer typId) {
        this.typId = typId;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }

    
    public Integer getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

}


