package com.dms.model.entity;

// Generated 26-May-2014 11:50:44 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.envers.Audited;

/**
 * User generated by hbm2java
 */
@Entity
@Audited
@Table(name = "user")
public class User extends BaseEntity implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USR_ID", unique = true, nullable = false)
	private Long usrId;

	@Column(name = "NAME", length = 4000)
	private String name;

	@Column(name = "PASSWORD", length = 4000)
	private String password;

	public User() {
	}

	public Long getUsrId() {
		return this.usrId;
	}

	public void setUsrId(Long usrId) {
		this.usrId = usrId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
